# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 570)
        MainWindow.setMinimumSize(QtCore.QSize(0, 68))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 570))
        MainWindow.setStyleSheet("*:focus {\n"
"  outline: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app.sizePolicy().hasHeightForWidth())
        self.app.setSizePolicy(sizePolicy)
        self.app.setMinimumSize(QtCore.QSize(0, 570))
        self.app.setMaximumSize(QtCore.QSize(16777215, 570))
        self.app.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app.setObjectName("app")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.app)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.app)
        self.header.setMaximumSize(QtCore.QSize(16777215, 0))
        self.header.setAutoFillBackground(True)
        self.header.setStyleSheet("")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.app_icon = QtWidgets.QFrame(self.header)
        self.app_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_icon.setObjectName("app_icon")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.app_icon)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.icon = QtWidgets.QLabel(self.app_icon)
        self.icon.setMaximumSize(QtCore.QSize(16, 16))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/icons/icons/box.svg"))
        self.icon.setScaledContents(True)
        self.icon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.icon.setObjectName("icon")
        self.horizontalLayout_4.addWidget(self.icon)
        self.text = QtWidgets.QLabel(self.app_icon)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.horizontalLayout_4.addWidget(self.text)
        self.horizontalLayout_2.addWidget(self.app_icon, 0, QtCore.Qt.AlignLeft)
        self.os_btn = QtWidgets.QFrame(self.header)
        self.os_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.os_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.os_btn.setObjectName("os_btn")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.os_btn)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.min_btn = QtWidgets.QPushButton(self.os_btn)
        self.min_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.min_btn.setStyleSheet("#min_btn {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(0, 255, 127);\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"}\n"
"\n"
"#min_btn:hover{\n"
"    border-color: rgb(0, 255, 127);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#min_btn:pressed {\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.min_btn.setText("")
        self.min_btn.setObjectName("min_btn")
        self.horizontalLayout_3.addWidget(self.min_btn)
        self.max_btn = QtWidgets.QPushButton(self.os_btn)
        self.max_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.max_btn.setStyleSheet("#max_btn {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 255, 127);\n"
"    border: 1px solid rgb(255, 255, 127);\n"
"}\n"
"\n"
"#max_btn:hover{\n"
"    border-color: rgb(0, 255, 127);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#max_btn:pressed {\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.max_btn.setText("")
        self.max_btn.setObjectName("max_btn")
        self.horizontalLayout_3.addWidget(self.max_btn)
        self.close_btn = QtWidgets.QPushButton(self.os_btn)
        self.close_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.close_btn.setStyleSheet("#close_btn {\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 65, 65);\n"
"    border: 1px solid rgb(255, 65, 65);\n"
"}\n"
"\n"
"#close_btn:hover{\n"
"    border-color: rgb(0, 255, 127);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#close_btn:pressed{\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.horizontalLayout_2.addWidget(self.os_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.container = QtWidgets.QFrame(self.app)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setMinimumSize(QtCore.QSize(0, 0))
        self.container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ffolder = QtWidgets.QFrame(self.container)
        self.ffolder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ffolder.setAutoFillBackground(True)
        self.ffolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ffolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ffolder.setObjectName("ffolder")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ffolder)
        self.horizontalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.save_path = QtWidgets.QLineEdit(self.ffolder)
        self.save_path.setMinimumSize(QtCore.QSize(500, 24))
        self.save_path.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_path.setFont(font)
        self.save_path.setStyleSheet("#save_path{\n"
"    border-radius: 4px;\n"
"    border: 1px solid red;\n"
"    padding: 0 8px;\n"
"}\n"
"\n"
"#save_path:hover {\n"
"    border-color: rgb(0, 255, 127);\n"
"}")
        self.save_path.setObjectName("save_path")
        self.horizontalLayout_8.addWidget(self.save_path)
        self.get_path_btn = QtWidgets.QPushButton(self.ffolder)
        self.get_path_btn.setMinimumSize(QtCore.QSize(80, 24))
        self.get_path_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.get_path_btn.setStyleSheet("#get_path_btn{\n"
"    border-radius: 4px;\n"
"    border: 1px solid red;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#get_path_btn:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"#get_path_btn:pressed{\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.get_path_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.get_path_btn.setIcon(icon)
        self.get_path_btn.setObjectName("get_path_btn")
        self.horizontalLayout_8.addWidget(self.get_path_btn)
        self.verticalLayout_2.addWidget(self.ffolder, 0, QtCore.Qt.AlignTop)
        self.furl = QtWidgets.QFrame(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.furl.sizePolicy().hasHeightForWidth())
        self.furl.setSizePolicy(sizePolicy)
        self.furl.setAutoFillBackground(True)
        self.furl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.furl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.furl.setObjectName("furl")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.furl)
        self.horizontalLayout_9.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.url = QtWidgets.QLineEdit(self.furl)
        self.url.setMinimumSize(QtCore.QSize(500, 24))
        self.url.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.url.setFont(font)
        self.url.setStyleSheet("#url{\n"
"    border-radius: 4px;\n"
"    border: 1px solid red;\n"
"    padding: 0 8px;\n"
"}\n"
"\n"
"#url:hover {\n"
"    border-color: rgb(0, 255, 127);\n"
"}")
        self.url.setObjectName("url")
        self.horizontalLayout_9.addWidget(self.url)
        self.download_btn = QtWidgets.QPushButton(self.furl)
        self.download_btn.setMinimumSize(QtCore.QSize(80, 24))
        self.download_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.download_btn.setStyleSheet("#download_btn{\n"
"    border-radius: 4px;\n"
"    border: 1px solid red;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#download_btn:hover{\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"#download_btn:pressed{\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.download_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_btn.setIcon(icon1)
        self.download_btn.setObjectName("download_btn")
        self.horizontalLayout_9.addWidget(self.download_btn)
        self.verticalLayout_2.addWidget(self.furl, 0, QtCore.Qt.AlignTop)
        self.fmsg = QtWidgets.QFrame(self.container)
        self.fmsg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fmsg.setAutoFillBackground(True)
        self.fmsg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmsg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmsg.setObjectName("fmsg")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.fmsg)
        self.horizontalLayout_10.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.fmsg)
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/activity.svg"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.msg = QtWidgets.QLabel(self.fmsg)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.msg.setFont(font)
        self.msg.setAlignment(QtCore.Qt.AlignCenter)
        self.msg.setObjectName("msg")
        self.horizontalLayout_10.addWidget(self.msg)
        self.label_3 = QtWidgets.QLabel(self.fmsg)
        self.label_3.setMaximumSize(QtCore.QSize(20, 20))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/activity.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.fmsg, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.fcontent = QtWidgets.QFrame(self.container)
        self.fcontent.setMaximumSize(QtCore.QSize(16777215, 500))
        self.fcontent.setStyleSheet("#fcontent:hover{\n"
"    border-color: rgb(0, 255, 127);\n"
"}")
        self.fcontent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fcontent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fcontent.setObjectName("fcontent")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.fcontent)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.table_content = QtWidgets.QTableWidget(self.fcontent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_content.sizePolicy().hasHeightForWidth())
        self.table_content.setSizePolicy(sizePolicy)
        self.table_content.setMinimumSize(QtCore.QSize(0, 400))
        self.table_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_content.setFont(font)
        self.table_content.setAutoFillBackground(True)
        self.table_content.setStyleSheet("")
        self.table_content.setObjectName("table_content")
        self.table_content.setColumnCount(4)
        self.table_content.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_content.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_content.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_content.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_content.setHorizontalHeaderItem(3, item)
        self.table_content.horizontalHeader().setCascadingSectionResizes(True)
        self.table_content.horizontalHeader().setDefaultSectionSize(160)
        self.table_content.horizontalHeader().setMinimumSectionSize(160)
        self.table_content.horizontalHeader().setSortIndicatorShown(False)
        self.table_content.horizontalHeader().setStretchLastSection(False)
        self.table_content.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_11.addWidget(self.table_content)
        self.verticalLayout_2.addWidget(self.fcontent, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.container, 0, QtCore.Qt.AlignTop)
        self.footer = QtWidgets.QFrame(self.app)
        self.footer.setAutoFillBackground(True)
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fcopyright = QtWidgets.QFrame(self.footer)
        self.fcopyright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fcopyright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fcopyright.setObjectName("fcopyright")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fcopyright)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.copyright = QtWidgets.QLabel(self.fcopyright)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.copyright.setFont(font)
        self.copyright.setStyleSheet("#copyright:hover{\n"
"    color: red;\n"
"    font-weight: bold;\n"
"}")
        self.copyright.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.copyright.setObjectName("copyright")
        self.horizontalLayout_6.addWidget(self.copyright, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_5.addWidget(self.fcopyright, 0, QtCore.Qt.AlignLeft)
        self.finfo = QtWidgets.QFrame(self.footer)
        self.finfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.finfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.finfo.setObjectName("finfo")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.finfo)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.expand_btn = QtWidgets.QPushButton(self.finfo)
        self.expand_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.expand_btn.setStyleSheet("#expand_btn {\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#expand_btn:hover{\n"
"    border-color: rgb(0, 255, 127);\n"
"}\n"
"\n"
"#expand_btn:pressed{\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.expand_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-down-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expand_btn.setIcon(icon2)
        self.expand_btn.setObjectName("expand_btn")
        self.horizontalLayout_7.addWidget(self.expand_btn)
        self.horizontalLayout_5.addWidget(self.finfo, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.footer, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.app, 0, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text.setText(_translate("MainWindow", "VING"))
        self.save_path.setPlaceholderText(_translate("MainWindow", "Save folder path"))
        self.url.setPlaceholderText(_translate("MainWindow", "Url download"))
        self.msg.setText(_translate("MainWindow", "...Đang lấy dữ liệu vui lòng đợi..."))
        item = self.table_content.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.table_content.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_content.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "URL NOWATERMARK"))
        item = self.table_content.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "STATUS"))
        self.copyright.setText(_translate("MainWindow", "Copyright by VING"))
import icons_rc
